version: '3.8'
services:
  web:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: research_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
